---
- hosts: all
  sudo: true
  vars:
    web_server: apachephp
    servername: sandbox.vb www.sandbox.vb 192.168.33.88
    timezone: UTC
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - apache
    - php5
    - mysql
    - composer
    - phpcommon
    - nodejs
    - devtools